force-app/main/default/objects/Showtime__c/Showtime__c.object-meta.xml
<CustomObject>
    <label>Showtime</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Showtime Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showtimes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showtime__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Malayalam</fullName>
            </value>
            <value>
                <fullName>Kannada</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Show_Format__c.field-meta.xml
<CustomField>
    <fullName>Show_Format__c</fullName>
    <label>Show Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2D</fullName>
            </value>
            <value>
                <fullName>3D</fullName>
            </value>
            <value>
                <fullName>4D</fullName>
            </value>
            <value>
                <fullName>IMAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Show_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Time__c</fullName>
    <label>Show Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateShowRecordsBatch.cls
global class CreateShowRecordsBatch implements Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, Name FROM Theater__c');
    }

    global void execute(Database.BatchableContext BC, List<Theater__c> theaterList) {
        List<Showtime__c> showRecords = new List<Showtime__c>();
        Time startTime = Time.newInstance(9, 0, 0, 0); // 9:00 am start time
        Time endTime = Time.newInstance(22, 0, 0, 0); // 10:00 pm end time
        
        List<Movie__c> movies = [SELECT Id, Name, Duration__c FROM Movie__c WHERE Duration__c != NULL AND IsShowing__c = true];
        
        for (Theater__c theater : theaterList) {
            Time currentShowTime = startTime;
            for (Movie__c movie : movies) {
                
                while (currentShowTime.addHours(3).millisecond() <= endTime.millisecond()) {
                    showRecords.add(new Showtime__c(
                        Theater__c = theater.Id,
                        Movie__c = movie.Id,
                        Show_Time__c = DateTime.newInstance(Date.today(), currentShowTime),
                        Show_Format__c = '2D',
                        Language__c = 'Hindi',
                        Price__c = 180
                    ));
                    
                    currentShowTime = currentShowTime.addHours(3);
                }
            }
            currentShowTime.addMinutes(25);
        }

        if (!showRecords.isEmpty()) {
            insert showRecords;
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}