force-app/main/default/objects/Showtime__c/Showtime__c.object-meta.xml
<CustomObject>
    <label>Showtime</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Showtime Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showtimes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showtime__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Show_Format__c.field-meta.xml
<CustomField>
    <fullName>Show_Format__c</fullName>
    <label>Show Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2D</fullName>
            </value>
            <value>
                <fullName>3D</fullName>
            </value>
            <value>
                <fullName>4D</fullName>
            </value>
            <value>
                <fullName>IMAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ShowtimeTriggerHandler.cls
public with sharing class ShowtimeTriggerHandler {
    public static void updateScreen(List<Showtime__c> showList){
        Set<Id> theaterIds=new Set<Id>();
        for(Showtime__c show : showList){
            //System.debug('>>> '+show.Theater__c);
            theaterIds.add(show.Theater__c);
        }
        
        System.debug('theaterIds>>>'+theaterIds);
        Map<Id,List<Screen__c>> mapOfIdAndListOfScreen = new  Map<Id,List<Screen__c>>();
        if(theaterIds.size()>0){
            List<Theater__c> theaters = [SELECT Id,(SELECT Id,Type__c from Screens__r) FROM Theater__c where Id IN :theaterIds];
            for(Theater__c theater:theaters){
                 mapOfIdAndListOfScreen.put(theater.Id,theater.Screens__r);
            }
            
        }
         System.debug('mapOfIdAndListOfScreen>>>'+mapOfIdAndListOfScreen);
        System.debug('showList>>>'+showList);
        for(Showtime__c show : showList){
            for(Screen__c screen : mapOfIdAndListOfScreen.get(show.Theater__c)){
                if(show.Show_Format__c.toLowerCase() == screen.Type__c.toLowerCase()){
                    show.Screen__c = screen.Id;
                }
            }
        }
         System.debug('showList>>>'+showList);
    }
}