force-app/main/default/objects/Showtime__c/Showtime__c.object-meta.xml
<CustomObject>
    <label>Showtime</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Showtime Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showtimes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showtime__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TheaterAndShowsHandlerTest.cls
@isTest
public class TheaterAndShowsHandlerTest {
    @testSetup static void setup() {     
          Movie__c createMovieRecord = TestDataFactory.createMovieRecord();
         insert createMovieRecord;
         Theater__c createTheaterRecord = TestDataFactory.createTheaterRecord();
         insert createTheaterRecord; 
         Showtime__c createShowtimeRecord = TestDataFactory.createShowtimeRecord(createMovieRecord.Id,createTheaterRecord.Id);
         insert createShowtimeRecord;
        Booking__c createBookingRecord = TestDataFactory.createBookingRecord(createMovieRecord.Id);
        createBookingRecord.Booking_Status__c ='Booked';
        createBookingRecord.Showtime__c = createShowtimeRecord.Id;
         insert createBookingRecord;
        
    }
    @isTest
    public static void getTheaterWithShowsTest(){
        String movieId = [SELECT Id FROM Movie__c limit 1].Id;
		test.startTest();
        	TheaterAndShowsHandler.getTheaterWithShows(movieId,'Ajmer',null);
        test.stopTest();
    }
    
    
    @isTest
    public static void getAlreadyBookedTicketsTest(){
        String showId = [SELECT Id FROM Showtime__c limit 1].Id;
		test.startTest();
        	TheaterAndShowsHandler.getAlreadyBookedTickets(showId);
        test.stopTest();
    }
    
    	@isTest
    public static void getTheaterWithMovieInfoTest(){
        String showId = [SELECT Id FROM Showtime__c limit 1].Id;
		test.startTest();
        	TheaterAndShowsHandler.getTheaterWithMovieInfo(showId);
        test.stopTest();
    }
	
}