force-app/main/default/objects/Showtime__c/Showtime__c.object-meta.xml
<CustomObject>
    <label>Showtime</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Showtime Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showtimes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showtime__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Show_Format__c.field-meta.xml
<CustomField>
    <fullName>Show_Format__c</fullName>
    <label>Show Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2D</fullName>
            </value>
            <value>
                <fullName>3D</fullName>
            </value>
            <value>
                <fullName>4D</fullName>
            </value>
            <value>
                <fullName>IMAX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ShowtimeTriggerHandlerTest.cls
@isTest
public class ShowtimeTriggerHandlerTest {
    @testSetup static void setup() {     
          Movie__c createMovieRecord = TestDataFactory.createMovieRecord();
         insert createMovieRecord;
         Theater__c createTheaterRecord = TestDataFactory.createTheaterRecord();
         insert createTheaterRecord;
        Screen__c createScreenRecord = TestDataFactory.createScreenRecord(createTheaterRecord.Id);
         insert createScreenRecord; 
         Showtime__c createShowtimeRecord = TestDataFactory.createShowtimeRecord(createMovieRecord.Id,createTheaterRecord.Id);
         insert createShowtimeRecord;
        
    }
    @isTest
    public static void updateScreenTest(){
        List<Showtime__c> shows = [select Id,Screen__c,Show_Format__c from Showtime__c];
		test.startTest();
        	ShowtimeTriggerHandler.updateScreen(shows);
        test.stopTest();
    }
    
	
}