force-app/main/default/objects/Showtime__c/Showtime__c.object-meta.xml
<CustomObject>
    <label>Showtime</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Showtime Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showtimes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Showtime__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Show_Time__c.field-meta.xml
<CustomField>
    <fullName>Show_Time__c</fullName>
    <label>Show Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Showtime__c/fields/Theater__c.field-meta.xml
<CustomField>
    <fullName>Theater__c</fullName>
    <label>Theater</label>
    <referenceTo>Theater__c</referenceTo>
    <relationshipLabel>Showtimes</relationshipLabel>
    <relationshipName>Showtimes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static Movie__c createMovieRecord (){
       Movie__c movie = new Movie__c();
		movie.Name = 'test movie';
        movie.Poster__c = 'https://assetscdn1.paytm.com/images/cinema/162917-b0808581-3e85-11ef-99b5-d35223c98590.jpg';
        movie.Release_Date__c = System.Today();
        return movie;
    }
    public static Theater__c createTheaterRecord (){
       Theater__c theater = new Theater__c();
		theater.Name  = 'pvr';
        theater.Location__City__s='Ajmer';
        return theater;
    } 
     public static Screen__c createScreenRecord (String theaterId){
            Screen__c screen = new Screen__c();
            screen.Screen_Label__c   = 'Secreen 1';
            screen.Theater__c  = theaterId;
            screen.Type__c = '2d';
            return screen;
        }
    public static Showtime__c createShowtimeRecord (String movieId,String theaterId){
       Showtime__c showtime = new Showtime__c();
		showtime.Movie__c  = movieId;
        showtime.Theater__c  = theaterId;
        showtime.Show_Time__c = System.now();
        return showtime;
    }
    public static Booking__c createBookingRecord (String movieId){
       Booking__c booking = new Booking__c();
		booking.Movie__c  = movieId;
        return booking;
    }
}